export const applicationsTypes = {
   RESET_APPLICATIONS: 'RESET_APPLICATIONS',
   SET_APPLICATIONS_DATA: 'SET_APPLICATIONS_DATA',
   SET_APPLICATIONS: 'SET_APPLICATIONS',
   UPDATE_APPLICATION: 'UPDATE_APPLICATION',
   REMOVE_APPLICATION: 'REMOVE_APPLICATION',
   SET_APPLICATION: 'SET_APPLICATION',
}
