export const postsTypes = {
   RESET_POSTS: 'RESET_POSTS',
   SET_POSTS_DATA: 'SET_POSTS_DATA',
   SET_POSTS: 'SET_POSTS',
   ADD_POSTS: 'ADD_POSTS',
   SET_POPULAR_POSTS_DATA: 'SET_POPULAR_POSTS_DATA',
   SET_POPULAR_POSTS: 'SET_POPULAR_POSTS',
   SET_RECENT_POSTS_DATA: 'SET_RECENT_POSTS_DATA',
   SET_RECENT_POSTS: 'SET_RECENT_POSTS',
   SET_POST: 'SET_POST',
   UPDATE_POST: 'UPDATE_POST',
   REMOVE_POST: 'REMOVE_POST',
   SET_INTERESTED: 'SET_INTERESTED',
}
