export const usersTypes = {
   RESET_USERS: 'RESET_USERS',
   SET_USERS_DATA: 'SET_USERS_DATA',
   SET_USERS: 'SET_USERS',
   ADD_USERS: 'ADD_USERS',
   UPDATE_USER: 'UPDATE_USER',
   REMOVE_USER: 'REMOVE_USER',
   SET_USER: 'SET_USER',
}
