export const subscribesTypes = {
   RESET_SUBSCRIBES: 'RESET_SUBSCRIBES',
   SET_SUBSCRIBES_DATA: 'SET_SUBSCRIBES_DATA',
   SET_SUBSCRIBES: 'SET_SUBSCRIBES',
   ADD_SUBSCRIBES: 'ADD_SUBSCRIBES',
   UPDATE_SUBSCRIBE: 'UPDATE_SUBSCRIBE',
   REMOVE_SUBSCRIBE: 'REMOVE_SUBSCRIBE',
   SET_SUBSCRIBE: 'SET_SUBSCRIBE',
}
