export const faqTypes = {
   RESET_FAQ: 'RESET_FAQ',
   SET_FAQ_DATA: 'SET_FAQ_DATA',
   SET_FAQ: 'SET_FAQ',
   ADD_FAQ: 'ADD_FAQ',
   UPDATE_FAQ: 'UPDATE_FAQ',
   REMOVE_FAQ: 'REMOVE_FAQ',
   SET_FAQ_ITEM: 'SET_FAQ_ITEM',
}
