export const authTypes = {
   SET_AUTH: 'SET_AUTH',
   SET_USER: 'SET_USER',
   SET_TOKEN: 'SET_TOKEN',
   SET_ROLE_IDS: 'SET_ROLE_IDS',
   SET_ROLE: 'SET_ROLE',
   SET_NOTIFICATIONS: 'SET_NOTIFICATIONS',
   SET_STEP: 'SET_STEP',
}

export const authStepTypes = {
   CHECK_EMAIL: 'CHECK_EMAIL',
   LOGIN: 'LOGIN',
   REGISTER: 'REGISTER',
   RESTORE: 'RESTORE',
}
