export const notificationsTypes = {
   RESET_NOTIFICATIONS: 'RESET_NOTIFICATIONS',
   SET_NOTIFICATIONS_DATA: 'SET_NOTIFICATIONS_DATA',
   SET_NOTIFICATIONS: 'SET_NOTIFICATIONS',
   ADD_NOTIFICATIONS: 'ADD_NOTIFICATIONS',
   UPDATE_NOTIFICATION: 'UPDATE_NOTIFICATION',
   REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
   SET_NOTIFICATION: 'SET_NOTIFICATION',
}
