export const pagesTypes = {
   RESET_PAGES: 'RESET_PAGES',
   SET_PAGES_DATA: 'SET_PAGES_DATA',
   SET_PAGES: 'SET_PAGES',
   ADD_PAGES: 'ADD_PAGES',
   UPDATE_PAGE: 'UPDATE_PAGE',
   REMOVE_PAGE: 'REMOVE_PAGE',
   SET_PAGE: 'SET_PAGE',
}
