export { default as Post } from './Post'
export { default as PostItem } from './PostItem'
export { default as Contacts } from './Contacts'
export { default as Courses } from './Courses'
export { default as CoursesItem } from './CoursesItem'
// export { default as CoursesLesson } from './CoursesLesson'
export { default as Events } from './Events'
export { default as EventsItem } from './EventsItem'
export { default as Faq } from './Faq'
export { default as Home } from './Home'
export { default as News } from './News'
export { default as PagesItem } from './PagesItem'
export { default as Partners } from './Partners'
export { default as Reviews } from './Reviews'
export { default as Subscribes } from './Subscribes'
export { default as Error } from './Error'
export { default as Login } from './Login'
export { default as UsersItem } from './UsersItem'

// CABINET
export { default as Cabinet } from './Cabinet'
export { default as CabinetStatistics } from './CabinetStatistics'
export { default as CabinetUser } from './CabinetUser'
export { default as CabinetContacts } from './CabinetContacts'
export { default as CabinetPosts } from './CabinetPosts'
export { default as CabinetPages } from './CabinetPages'
export { default as CabinetSubscribes } from './CabinetSubscribes'
export { default as CabinetFaq } from './CabinetFaq'
export { default as CabinetSupport } from './CabinetSupport'
export { default as CabinetComments } from './CabinetComments'
export { default as CabinetSettings } from './CabinetSettings'

// EVENTS
export { default as CabinetEvents } from './CabinetEvents'
export { default as CabinetEventsAdd } from './CabinetEventsAdd'
export { default as CabinetEventsItem } from './CabinetEventsItem'

// NOTIFICATIONS
export { default as CabinetNotifications } from './CabinetNotifications'
export { default as CabinetNotificationsAdd } from './CabinetNotificationsAdd'

// COURSES
export { default as CabinetCourses } from './CabinetCourses'
export { default as CabinetCoursesAdd } from './CabinetCoursesAdd'
export { default as CabinetCoursesItem } from './CabinetCoursesItem'
export { default as CabinetCoursesLessons } from './CabinetCoursesLessons'
export { default as CabinetCoursesLesson } from './CabinetCoursesLesson'
export { default as CabinetCoursesLessonTest } from './CabinetCoursesLessonTest'
export { default as CabinetCoursesLessonEdit } from './CabinetCoursesLessonEdit'
