export const commentsTypes = {
   RESET_COMMENTS: 'RESET_COMMENTS',
   SET_COMMENTS_DATA: 'SET_COMMENTS_DATA',
   SET_COMMENTS: 'SET_COMMENTS',
   ADD_COMMENTS: 'ADD_COMMENTS',
   SET_COMMENT_ADDED: 'SET_COMMENT_ADDED',
}
